/* 
 * File:   mcal_interrupt_config.h
 * Author: OMEN
 *
 * Created on October 22, 2023, 4:29 PM
 */

#ifndef MCAL_INTERRUPT_CONFIG_H
#define	MCAL_INTERRUPT_CONFIG_H


/*Section: Includes*/

#include "avr/io.h"
#include "../../MCAL_LAYER/MCAL_STD_LIB.h"
#include "../../MCAL_LAYER/GPIO/GPIO.h"
#include "mcal_interrupt_gen_cfg.h"


/*  Section: Macro Declarations  */

#define INTERRUPT_ENABLE   1
#define INTERRUPUT_DISABLE 0
#define INTERRUPUT_OCCUR     1
#define INTERRUPUT_NOT_OCCUR 0
//#define INTERRUPUT_PRIORITY_ENABLE  1
//#define INTERRUPUT_PRIORITY_DISABLE 0

/*  Section: Macro Functions Declarations  */
//
//#if INTERRUPUT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
///*  THIS MCRO WILL ENABLE PRIORITY LEVELS ON INTERRUPT  */
//#define INTERRUPT_PRIOITYLEVELSENABLE() (RCONbits.IPEN = 1)
///*  THIS MCRO WILL DISABLE PRIORITY LEVELS ON INTERRUPT  */
//#define INTERRUPT_PRIOITYLEVELSDISABLE() (RCONbits.IPEN = 0)
//
///*  THIS MACRO WILL ENABLE HIGH PRIORITY GLOBAL INTERRUPT*/
//#define INTERRUPT_GLOBALINTERRUPTHIGHENABLE() (INTCONbits.GIEH = 1)
///*  THIS MACRO WILL DISABLE HIGH PRIORITY GLOBAL INTERRUPT*/
//#define INTERRUPT_GLOBALINTERRUPTHIGHDISABLE() (INTCONbits.GIEH = 0)
//
///*  THIS MACRO WILL ENABLE LOW PRIORITY GLOBAL INTERRUPT*/
//#define INTERRUPT_GLOBALINTERRUPTLOWENABLE() (INTCONbits.GIEL = 1)
///*  THIS MACRO WILL DISABLE LOW PRIORITY GLOBAL INTERRUPT*/
//#define INTERRUPT_GLOBALINTERRUPTLOWDISABLE() (INTCONbits.GIEL = 0)
//#else
/*  THIS MACRO WILL ENABLE GLOBAL INTERRUPT*/
#define INTERRUPT_GLOBALINTERRUPTENABLE() (SET_BIT(SREG,SREG_I));
/*  THIS MACRO WILL DISABLE GLOBAL INTERRUPT*/
#define INTERRUPT_GLOBALINTERRUPTDISABLE() (CLEAR_BIT(SREG,SREG_I))

///*  THIS MACRO WILL ENABLE PERIPHERAL INTERRUPT*/
//#define INTERRUPT_PERIPHERALINTERRUPTENABLE() (INTCONbits.PEIE = 1)
///*  THIS MACRO WILL DISABLE PERIPHERAL INTERRUPT*/
//#define INTERRUPT_PERIPHERALINTERRUPTDISABLE() (INTCONbits.PEIE = 0)
//#endif
 
/*  Section: Data Type Declarations  */

 
/*  Section: Functions Declarations  */


#endif	/* MCAL_INTERRUPT_CONFIG_H */

